export const REDUX = {
	//PRODUCT REDUCER
	UPDATE_PRODUCT_LIST: 'UPDATE_PRODUCT_LIST',
	UPDATE_PRODUCT_INFO: 'UPDATE_PRODUCT_INFO',
	CLEAR_DATA: 'CLEAR_DATA',
	// User reducer
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	//CustomerReducer
	UPDATE_CUSTOMER_LIST: 'UPDATE_CUSTOMER_LIST',
	UPDATE_CUSTOMER_INFO: 'UPDATE_CUSTOMER_INFO',
	// order reducer
	UPDATE_ORDER_LIST: 'UPDATE_ORDER_LIST',
	UPDATE_ORDER_INFO: 'UPDATE_ORDER_INFO',
};
